### ISSUE TITLE
Pro Micro v 1.3 schematic has Arduino IDE pin 14 and 17 labels swapped

### ISSUE THREAD

**Issue by dmjlambert** [sparkfun/Pro_Micro#1]
Arduino Pin 14 is 32U4 pin 11/MISO and Arduino Pin 17 is 32U4 pin 8/SS which is connected to the RXLED

**Comment by BrentWilkins** [comment]
Fixed.  We were using an old version of the ATmega32U4 part.  Thanks!

**Comment by dmjlambert** [comment]
I'm sorry Brent, I was not clear and I should have given you more details.   I'm afraid the changes you made were not what I was talking about, could you please revert it back and make different changes?
 Could you please have a look at this attached picture?
![clarification about arduino pins 14 and 17](https://cloud.githubusercontent.com/assets/12522672/8265673/c543cfa6-16c9-11e5-8ab2-86f25cdc3c96.png)

**Comment by BrentWilkins** [comment]
No, you were plenty clear to me.  I fixed it in the v13.1_3.3V branch.  I did so by using current library parts which caused copper to be negligibly altered.  Can't release that until it's proto'd since it's a hot product.  Not sure why the main branch is still wrong.  Feel free to use the v13.1 (3.3V) branch as a reference.
